### PR TITLE
1.14 update

### PR DESCRIPTION
**Pull request by Nowaha**
It'd be nice if we merged this :)

### CODE REVIEW

**Comment by Huskehhh** [comment]
Yeah, I'm all for it. Just gotta fix the conflicts. :)

**Comment by Huskehhh** [comment]
Okay. This merge should work now.

**Review by Huskehhh — APPROVED** [review]

**Comment by Nowaha** [comment]
Alright. I never know how to fix conflicts haha I have no idea what to do. Thanks!

**Comment by Nowaha** [comment]
I have no idea if something is ruined because I also merged someone else's code (which was pretty broken).

**Comment by Huskehhh** [comment]
> 
> 
> I have no idea if something is ruined because I also merged someone else's code (which was pretty broken).

No it's okay. I had to merge the upstream changes before the pull request would go through. :)

**Pull request merged**
